### PR TITLE
Implement cargo-audit testing in travis

### LINKED ISSUE #9: Implement cargo-audit testing for new pull requests
We'd like to enforce [`cargo-audit`](https://blog.rust-lang.org/inside-rust/2019/10/03/Keeping-secure-with-cargo-audit-0.9.html) testing on all new pull requests via Travis. This should be an augmentation to the existing Travis configuration.

### PR DESCRIPTION
**Pull request by mbestavros**
Resolves #9.

### CODE REVIEW

**Comment by mbestavros** [comment]
@steveeJ I cannot add reviewers myself on this repo; tagging you for review.

**Review by steveej — APPROVED** [review]

**Review by steveej — COMMENTED** [review]
After my approval I double-checked and looked for the *Cargo.lock* in this project, which doesn't exist. I'm surprised that `cargo audit` works without it. @mbestavros Do you know why?

**Comment by mbestavros** [comment]
@steveeJ Seems like running `cargo-audit` locally without a lockfile generates one before running. So the `cargo generate-lockfile` line the `cargo-audit` repo recommends adding to the config may not even be necessary.

It still might be good to add for consistency with the official recommendations. Thoughts?

**Comment by steveej** [comment]
> Seems like running `cargo-audit` locally without a lockfile generates one before running. So the `cargo generate-lockfile` line the `cargo-audit` repo recommends adding to the config may not even be necessary.

Are the generated lockfiles equivalent?



> It still might be good to add for consistency with the official recommendations. Thoughts?

Yes, running it explicitly definitely helps my confusion ;-) Otherwise we'd have to verify if the generation algorithms are equivalent.

We could write a helper script for installing cargo audit, which checks if a lockfile exists and generate one if not and print a line that it generated one.

**Review by steveej — APPROVED** [review]

**Review by steveej — APPROVED** [review]

**Pull request merged**
